#!/bin/bash

#SBATCH -J Generate_and_Save_Thermal_Fin_Data
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH -n 4
#SBATCH -t 12:00:00
#SBATCH -o Generate_and_Save_Thermal_Fin_Data.out
#SBATCH --mail-user=Hwan.Goh@gmail.com
#SBATCH --mail-type=all

module load intel/17.0.4 python3/3.6.3 cuda/10.0 cudnn/7.6.2 nccl/2.4.7

source activate fenicsproject

ibrun ./Generate_and_Save_Thermal_Fin_Data.py
